### ISSUE TITLE
Customer VAT vs. Trader name etc.

### ISSUE THREAD

**Issue by bosue** [alyf-de/erpnext_germany#14]
Nice VAT checker!
A feature ERPNext should definitely ship with IMO, after getting polished a little bit. Finally, every company in the EU needs this functionality, plus quite a few abroad who do a lot of business with the EU.

The terminology however confused me quite a bit. The VAT field itself explicitly refers to customers, while all other fields refer to some trader. With the English interface, it also took me a bit to understand that the difference doesn‘t seem to be on purpose:
![IMG_1292](https://github.com/alyf-de/erpnext_germany/assets/46800703/15060d73-3d31-489e-8811-f0adb088ae6e)

We neither want to limit the VAT feature to customers nor to traders or suppliers. So how about referring to „Business Partners“ or simply „Counterparty“? There are a few more – and more important – things to do, but it makes sense to start with a proper, consistent terminology. So if you agree and support one or the other choice of terminology, I can readily post a PR.

**Comment by barredterra** [comment]
Hi, thanks for the feedback. These decisions were made on purpose:

- As far as I know, we are only obliged to check the VAT ID of our customers (to make sure they are registered and will adhere to the reverse charge procedure). That's why we can select entries from the **Customer** doctype to pre-fill the **VAT ID Check**. That's also why the name is consistent with the rest of ERPNext.
- The other fields containing "Trader" are input or output parameters of the VIES API. They are named exactly like the API parameters to make it clear which data is coming to/from the API and which is just meta data or connections for ERPNext.
