### ISSUE TITLE
VAT ID  and Tax ID should be two different fields

### ISSUE THREAD

**Issue by ne-mmg** [alyf-de/erpnext_germany#15]
The doctype "VAT_ID_Check" is fetching the values for "Customer VAT ID" field from "customer.tax_id" and the field value for "Requester VAT ID" is fetching from "company.tax_id"

The "customer.tax.id" is the "Steuernummer" of the customer.
The "company.tax_id" field is representing the "Steuernummer" of the company

"Steuernummer"(Tax ID) is different from "USt-IdNr"(VAT ID).
This is somehow misleading if Tax ID is used for VAT ID. these should be two different fields.

There is no "VAT ID" field by default in ERPNext. We created a custom field for the "USt-IdNr." in the customer doctype

Maybe it is a good idea to add a custom field e.g. "Customer VAT ID" and fetch from there.

**Comment by barredterra** [comment]
There are almost no cases where you actually need the german "Steuernummer". We can just assume that, for European companies, it usually holds the USt-IdNr. This saves a lot of custom fields and has the same functionality. If you like, you can add a custom Translation "Tax ID" -> "USt-IdNr" so that it's less confusing.

**Comment by ALTAPLAN** [comment]
For our usecase, we also need separate fields for USt-Idnr and Steuernummer. Using one as the other is even more confusing.

You may need the Steuernummer whenever a business partner doesn't have a USt-Idnr. Many "Freiberufler" (freelancer) and "Einzelgewerbe" (one-person-entrepreneurs) and even some SMEs actually don't have a USt-Idnr. or don't use it. Unfortunately, there is no requirement to have one, even less to use it, unless borders are crossed.

Almost no cases? I'd rather say about a fourth or a fifth of our customers. And while in many cases we won't ever need the USt-Idnr of a customer, in quirte a few cases customers are suppliers at the same time (e.g. Sale-and-lease back). In this case, we need either the USt-Idnr or the Steuernummer, whatever is available, to print a reverse billing invoice ("Gutschrift"). Same with many commission recipients.

Sure, our business case may be slightly unorthodox, but then again, @ne-mmg for some reason has the same need.

Of course, we can create a separate field and override the "Tax ID" field's translation, and will do so. But then again, if ppl have to reinvent even the most basic stuff to adapt ERPNext to local customs before even getting started, it seems like an semioptimal "Welcome to ERPNext" banner.

And certainly this isn't the largest barrier to Germany compliance. There are dozens more, and of course, there are always more important things to do. But hey, how nice, there's someone raising a valid issue - isn't this a good reason to start exactly here? ;)

**Comment by bosue** [comment]
For our usecase, we also need separate fields for USt-Idnr and Steuernummer. Using one as the other is even more confusing.

You may need the Steuernummer whenever a business partner doesn't have a USt-Idnr. Many "Freiberufler" (freelancer) and "Einzelgewerbe" (one-person-entrepreneurs) and even some SMEs actually don't have a USt-Idnr. or don't use it. Unfortunately, there is no requirement to have one, even less to use it, unless borders are crossed.

Almost no cases? I'd rather say about a fourth or a fifth of our customers. And while in many cases we won't ever need the USt-Idnr of a customer, in quirte a few cases customers are suppliers at the same time (e.g. Sale-and-lease back). In this case, we need either the USt-Idnr or the Steuernummer, whatever is available, to print a reverse billing invoice ("Gutschrift"). Same with many commission recipients.

Sure, our business case may be slightly unorthodox, but then again, @ne-mmg for some reason has the same need.

Of course, we can create a separate field and override the "Tax ID" field's translation, and will do so. But then again, if ppl have to reinvent even the most basic stuff to adapt ERPNext to local customs before even getting started, it seems like an semioptimal "Welcome to ERPNext" banner.

And certainly this isn't the largest barrier to Germany compliance. There are dozens more, and of course, there are always more important things to do. But hey, how nice, there's someone raising a valid issue - isn't this a good reason to start exactly here? ;)

**Comment by barredterra** [comment]
Correct me if I'm wrong, but, as far as I know, there's no legal (or even business) requirement to record the _Steuernummer_.

We only need to record and validate the _USt-IdNr_ in case of reverse charge  B2B sales. For other cases, it's enough if the supplier's tax ID is printed on the invoice. I'd prefer to keep using the existing fields for the former, rather than inventing new fields for a number we don't need to record.

**Comment by bosue** [comment]
There is no obligation to store the "Steuernummer" for every single business partner, that's true.

However, there are several situations where _either_ the USt-IDnr _or_ the Steuernummer is needed:
1.) Reverse Charge (VAT payable by the customer)
a.) within the same country (Steuerschuldumkehr, §§ 3a Abs. 2, 3b, 13b, 25b UStG): USt-Idnr _or_ Steuernr.
b.) cross-border within the EU (Innergemeinschaftslieferung, § 6a UStG): USt-Idnr required, AFAIK
2.) Reverse Billing (VAT payable by the supplier, but invoice or "Gutschrift" created by the customer, § 14 Abs. 4 Satz 1 Nr. 10 UStG): USt-Idnr _or_ Steuernummer

Information on case 2:
- https://www.haufe.de/finance/haufe-finance-office-premium/gutschriften-die-5-haeufigsten-missverstaendnisse-und-fehler-21-steuernummer-des-ausstellers-der-gutschrift_idesk_PI20354_HI2347939.html
- https://www.deutsche-handwerks-zeitung.de/so-muss-ihre-gutschrift-kuenftig-aussehen-138858/
- https://www.ihk.de/ostbrandenburg/zielgruppeneinstieg-gruender/steuern-und-finanzen/pflichtangaben-auf-rechnungen-1957938

Now if any of these situations arise,and you don't have a business partner's USt-Idnr, either because the partner doesn't have one or doesn't use/communicate it, then you need the Steuernummer instead. This may only happen to us once or twice a year or so, but still... 💁🏻‍♂️

**Comment by ne-mmg** [comment]
> This saves a lot of custom fields and has the same functionality.

We only needed two custom fields. What do you mean by "a lot of custom fields" maybe we are missing something?

We simply added a custom field to the "Customer" doctype as well as the "Company" doctype. 
This lets us use the individual expressions in e.g. jinja without possibly or eventually collide with any other issues that we don't oversee - at least until now.

Simply translating "Tax ID" is of course messing up the translation in the "company.tax_id" as well. Therefore the variable can no longer be used for "Steuernummer". So we would need to add an additional "hardcoded" alternative which doesn't seem nice.

I really think the extension works wonderful und adds a lot value to ERPNext, it's just a suggestion to enhance the ux-experience.

Great work

**Comment by barredterra** [comment]
> We only needed two custom fields. What do you mean by "a lot of custom fields" maybe we are missing something?

The _Tax ID_ is also fetched into transactions. Because there are a lot of transactions, that makes a lot of fields.

I still don't see a good reason why we wouldn't just put both numbers in the same field. Both are a _Tax ID_. We only ever need one of the two. Keeps things much simpler for now.

**Comment by bosue** [comment]
> The Tax ID is also fetched into transactions. Because there are a lot of transactions, that makes a lot of fields.

Ahhh. Probably this is the original reason for your scepticism, and it‘s definitely a good reason not to prematurely add a second, custom Tax ID field unless unavoidable. 🤷🏻‍♂️

> Both are a Tax ID. We only ever need one of the two.

That‘s true. Need to figure out how everything will play out with the field being used for a mix of two different kinds of ID though.
