### ISSUE TITLE
Feature request EU VAT validation from suppliers

### ISSUE THREAD

**Issue by billy995** [alyf-de/erpnext_germany#16]
Is it possible to add a check of suppliers?

**Comment by barredterra** [comment]
Hi @billy995 , currently no. What's your use case?

**Comment by billy995** [comment]
I would like to check periodically if  suppliers still exist and, if I take on new ones, whether they exist before I place an order and pay in advance

**Comment by bosue** [comment]
See #14.

It is true that under the Reverse Charge scheme only the customer‘s VAT ID needs to be validated.

However, there is a number of cases in which the supplier’s (valid) VAT ID has to be recorded and printed on documents such as a “Gutschrift” in Germany.

The VAT ID needs to be valid, otherwise the company has to prove it received the invalid VAT ID from the supplier.

![IMG_1817](https://github.com/alyf-de/erpnext_germany/assets/46800703/b9f7ae68-bd36-413b-96f3-88806f1d215b)

Sources:
- [IHK](https://www.ihk.de/ostbrandenburg/zielgruppeneinstieg-gruender/steuern-und-finanzen/pflichtangaben-auf-rechnungen-1957938#:~:text=der%20Steuernummer%20bzw.-,der%20USt%2DIdNr.,seine%20Steuernummer%20oder%20USt%2DIdNr.)
- [Haufe](https://www.haufe.de/finance/haufe-finance-office-premium/gutschriften-die-5-haeufigsten-missverstaendnisse-und-fehler-21-steuernummer-des-ausstellers-der-gutschrift_idesk_PI20354_HI2347939.html)

It may not be formally required to verify the supplier‘s VAT ID, but of course, everyone would try to avoid such a situation by verifying the VAT ID in the first place. Be it to avoid an input error, to check commercial status, avoid fraudulent suppliers or simply to make sure the supplier gave the correct VAT ID.

More generally, verifying the supplier‘s VAT is also considered one of the available measures to double-check the proper existence of an invoicing supplier.

**Comment by barredterra** [comment]
Makes sense, will implement this

**Comment by barredterra** [comment]
https://github.com/alyf-de/erpnext_germany/releases/tag/v15.1.0
https://github.com/alyf-de/erpnext_germany/releases/tag/v14.4.0
